/**
  *MagicTelecomAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
  */

'use strict';
angular.module('MagicTelecomAPILib').factory('UsersController',function($q,Configuration,HttpClient,APIHelper){
    return{
        /**
         * Allow clients to test authentication.
         *
         * @return {promise<mixed>}
         */
        getAuthentications : function(){

            //prepare query string for API call
            var baseUri = Configuration.BASEURI
            var queryBuilder = baseUri + "/authentications";
            
            //validate and preprocess url
            var queryUrl = APIHelper.cleanUrl(queryBuilder);
            
            //prepare headers
            var headers = {
                "accept" : "application/json",
                "X-Auth-Token" : Configuration.xAuthToken
            };

            //prepare and invoke the API call request to fetch the response
            var config = {
                method : "GET",
                queryUrl : queryUrl,
                headers: headers,
            };
            
            var response = HttpClient(config);
                    
            //Create promise to return
            var deffered= $q.defer();
                    
            //process response
            response.then(function(result){
                deffered.resolve(result.body);
            },function(result){
                //Error handling for custom HTTP status codes
                if (code == 401) {
                    deffered.reject(APIHelper.appendContext({errorMessage: "You are not authenticated", errorCode: 401, errorResponse: result.message},result.getContext()));
                    return;
                } else if (code == 403) {
                    deffered.reject(APIHelper.appendContext({errorMessage: "This action needs a valid WSSE header", errorCode: 403, errorResponse: result.message},result.getContext()));
                    return;
                } else if (code == 400) {
                    deffered.reject(APIHelper.appendContext({errorMessage: "Http bad request", errorCode: 400, errorResponse: result.message},result.getContext()));
                    return;
                } else {
                    deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: result.code, errorResponse: result.message},result.getContext()));
                }
            });
            
            return deffered.promise;
        }
    }
});