/**
 *MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
 */

'use strict';
angular.module('MagicTelecomAPILib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "https://api.magictelecom.com/app_dev.php",

        //API Token
        xAuthToken : "123abcqwerty"

    };
});

