/**
 *MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
 */
/**
 * Creates a instance of CdrForm
 *
 * @constructor
 */
function CdrForm() {
    this.cdrs = null;     
}

CdrForm.prototype = new BaseModel();
CdrForm.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {Cdrs}
 */
CdrForm.prototype.getCdrs = function() {
    return this.cdrs;
};

/**
 * Setter for Cdrs
 * 
 * @param {Cdrs} value 
 */
CdrForm.prototype.setCdrs = function(value) {
    this.cdrs = value;
};





