/**
 *MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/22/2016
 */
/**
 * Creates a instance of TrunkForm
 *
 * @constructor
 */
function TrunkForm() {
    this.trunk = null;     
}

TrunkForm.prototype = new BaseModel();
TrunkForm.prototype.constructor = BaseModel;

/**
 * TODO: Write general description for this method
 *
 * @return {Trunk}
 */
TrunkForm.prototype.getTrunk = function() {
    return this.trunk;
};

/**
 * Setter for Trunk
 * 
 * @param {Trunk} value 
 */
TrunkForm.prototype.setTrunk = function(value) {
    this.trunk = value;
};





